local generatorFilename = arg[1]
local packagePath = arg[2]
local dictionaryFile = arg[3]
local outputFile = arg[4]
local readableOutputFile = arg[5]

-- Update the package path so that we can load primary source modules
package.path = packagePath .. package.path

local wordGraphModule = require('wordgraph')

local function printHeader(file, generatorFilename, dictionaryFile)
    file:write('-- \n-- AUTO-GENERATED FILE - DO NOT MODIFY MANUALLY\n')
    file:write('-- \n-- This file has been generated by ' .. generatorFilename .. ',\n')
    file:write('-- using data from, ' .. dictionaryFile .. '\n')
    file:write('-- \n')
end

local function main()
    local graph = wordGraphModule.WordGraph:new(dictionaryFile)

    local export = function(filename, readableOutput)
        local file = io.open(filename, 'w')
        printHeader(file, generatorFilename, dictionaryFile)
        graph:serialize(file, readableOutput)
        file:close()
    end

    -- Generate a
    export(outputFile, false)
    export(readableOutputFile, true)
end


main()