local generatorFilename = arg[1]
local packagePath = arg[2]
local dictionaryFile = arg[3]
local outputFile = arg[4]

-- Update the package path so that we can load primary source modules
package.path = packagePath .. package.path

local wordGraphModule = require('wordgraph')

--print('Generator File: ' .. generatorFilename)
--print('Package Path: ' .. package.path)
--print('Dictionary File: ' .. dictionaryFile)
--print('Output File: ' .. outputFile)

local function printHeader(file, generatorFilename, dictionaryFile)
    file:write('-- \n-- AUTO-GENERATED FILE - DO NOT MODIFY MANUALLY\n')
    file:write('-- \n-- This file has been generated by ' .. generatorFilename .. ',\n')
    file:write('-- using data from, ' .. dictionaryFile .. '\n')
    file:write('-- \n')
end

local function main()
    local file = io.open(outputFile, 'w')
    printHeader(file, generatorFilename, dictionaryFile)

    local graph = wordGraphModule.WordGraph:new(dictionaryFile)
    graph:serialize(file)

    file:close()
end


main()